### ISSUE TITLE
KeyError: 'model_save_path' error

### ISSUE THREAD

**Issue by chulyoung-code** [captanlevi/Contour-Detection-Pytorch#5]
hi your code is very useful for me! thank you for your kind and smart

I wanted to train the autonomous vehicle data, so I tried to train 7000 pieces of data, but first I trained only 181 pieces of data to match the name with train.txt.
but I got some problem KeyError: 'model_save_path' error can I help you?
![error](https://user-images.githubusercontent.com/66548733/115205178-3edd6480-a134-11eb-9d55-0d18d3fb5bbf.png)

**Comment by captanlevi** [comment]
Hello , thanks for using the code , you will see on line 22 of train.py a dictionary names "paths" , just add a key "model_save_path", and set its value to the folder where you want to save your trained models 

hope it helps

**Comment by chulyoung-code** [comment]
wow, thank you!! I will try it

thank you for your help

**Comment by kulkarnikeerti** [comment]
Hi @chulyoung-code
How long did it take for you to start the model training? Did you use the mutliprocessing? Because, my model is not able to start the training not sure if its because of multi processing, it just stuck at checking if the `shared Q` is empty and its always empty for some reason. Did you have similar kind of problem?
